### PR TITLE
Division with experimental

### PR DESCRIPTION
**Pull request by aehyvari**
Implements the logic for experimental divisions on a track in scoring

### CODE REVIEW

**Comment by jhoenicke** [comment]
looks good to me.  One minor nit: `md_comp_get_value` is no longer needed, right?  Maybe remove it.

**Comment by aehyvari** [comment]
Yes, thanks, I removed it.  The scoring script would need some bigger refactoring.  It might be possible to separate the scoring from the reporting to maybe different files.  But let's do that on a different PR.

**Comment by aehyvari** [comment]
If nobody objects, I'm going to merge the stuff this evening and update the website so we get the new data out.

**Comment by jhoenicke** [comment]
Looks good now but didn't test it.

**Comment by aehyvari** [comment]
I ran it on this year's competition, it gives the same results as the smtcomp2020 tagged version, apart from the winners for MV.  I didn't test it on previous years' competitions though, but that's less critical I guess.

**Pull request merged**
