### PR TITLE
Changing YAML division generation for new divisions

### PR DESCRIPTION
**Pull request by HanielB**

### CODE REVIEW

**Review by jhoenicke — CHANGES_REQUESTED** [review]
I would like to keep these scripts working for older years, too.  I'm not sure how much work it is.  It looks like you need to have a `if year >=2021` in the division parser and the output routine.  Then set the logic2division dictionary to map each logic to itself for older years and the remaining code may be left as is.

What do you think?

**Comment by HanielB** [comment]
I have updated the script and the only difference to what we'd produce for example for 2020 is that the division files do not contain the tracks where there are no benchmarks. I assume that does not make a difference? In that case, I think that this would be good to go then.

**Review by jhoenicke — APPROVED** [review]

**Comment by jhoenicke** [comment]
I added some small changes, mainly sorting the logics in the output.

I have some differences in the number of benchmarks in the web-site output, is it normal?  I'm certainly still missing the cloud track benchmark selection.

**Comment by HanielB** [comment]
I'm gonna check.

**Comment by HanielB** [comment]
I'm getting the same numbers as currently in the website for 2021. Maybe it's because you're considering non-competing (which I had considered before)?

**Pull request merged**
